### ISSUE TITLE
Beacon values reading is not consistent, gap between two beacon reading is around 8 to 10s depening on phone

### ISSUE THREAD

**Issue by gptshubham595** [AltBeacon/android-beacon-library#1116]
### Expected behavior
    Beacon reaading should be consistent gap between two beacon reading should be less than 2 sec

### Actual behavior
    Beacon reaading is inconsistent gap between two beacon reading is more than 8 to 10 sec in some phones

### Steps to reproduce this behavior
    Install altbeacon reference apk and take readings

### Mobile device model and OS version
    Device: Oppo F1s/Vivo
    OS: Android 12

### Android Beacon Library version
    altbeacon_version = "2.19.4"

**Comment by davidgyoung** [comment]
A few questions:

1. Do you experience this with the app visible in the foreground, or only in the background?

2. What settings are you using for beaconManager.setScanPeriod(...) and beaconManager.setBetweenScanPeriod(...)?  (Do you customize this or use the defaults)

3. For the beacon you are using to test, if you install the BeaconScope app from the Google Play store, what does it tell you that the advertising rate is?  (The app will show this as a value in Hz)

**Comment by gptshubham595** [comment]
![Screenshot_2022-12-27-18-39-56-27_0889de87cee1e794594475e7f6a57b34](https://user-images.githubusercontent.com/24877361/209794941-0fdabf2f-27ed-4675-8f86-a30d66a0a036.jpg)

**Comment by davidgyoung** [comment]
Does the screenshot labelled "Vivo Mobile" correspond to "Device: Oppo F1s, OS: Android 12" as mentioned in the issue?

**Comment by gptshubham595** [comment]
Means this issue was observed majorly in vivo and oppo

**Comment by gptshubham595** [comment]
I read this, and found OS Bluetooth chips are not configurable
https://stackoverflow.com/questions/62609250/android-beacon-library-long-search-time

so we cannot override or do anything?

**Comment by davidgyoung** [comment]
The problem is most likely specific to a customization of the oppo/vivo/oneplus Bluetooth stacks in the closed-source  code forked from the Android Open Source project.  The code you show is likely modified in unknown ways by the manufacturer and this may be the driver of your observations.

It is possible there are workarounds to improve this, but finding them requires time consuming low-level tests with the Android Bluetooth scanning APIs in various conditions (foreground, background, screen on, screen off, etc) to document differences from the AOSP behavior seen on Google Pixel devices when scanning for a reference beacon.
