### ISSUE TITLE
Nexus 5 Android 5.0 no use 5.0 API

### ISSUE THREAD

**Issue by niqt** [AltBeacon/android-beacon-library#147]
Hi,
on my nexus 5 update with 5.0 (official update) the library doens't use the Android 5.0 api as wrote in the doc:
"On Android 5.0, new scanning APIs allow for more efficient background scanning that saves provide similar power scanning to the technique described above, but with much faster beacon detection times. Instead of it taking up to five minutes to detect a beacon (with the defaults described above), it detections take place within a few seconds."
If i don't use:
        // set the duration of the scan to be 1.1 seconds
        beaconManager.setBackgroundScanPeriod(1100l);
// set the time between each scan to be 1 hour (3600 seconds)
        beaconManager.setBackgroundBetweenScanPeriod(11000l);

I have a scanning every 5 minutes (as default).

**Comment by davidgyoung** [comment]
Sorry, the documentation was not very clear on how this works.  If you have beacons transmitting in the vicinity while the Android 5 device is in the background it will behave like you describe.  I have updated the documentation to disclose this:


On Android 5.0, new scanning APIs allow for more efficient background scanning that saves provide similar power savings to the technique described above, but with much faster beacon detection times.  Instead of  it taking up to five minutes to detect a beacon (with the defaults described above), it detections of new beacons generally take place within a few seconds.

This technique works by constantly doing a low power scan for beacons when the app is in the background.  This constant low power scan will typically deliver a callback within 5 seconds of a new beacon being seen.  If beacons continue to be present while the app is in the background, the app will start doing periodic scans like in Android 4.x using the same technique described above.  Once all beacons disappear, it will resume doing a constant scan in the background for fastest
response times.
