### ISSUE TITLE
How to find my Kontact Beacon Layout??

### ISSUE THREAD

**Issue by kiledar2006** [AltBeacon/android-beacon-library#202]
i have purchased new Kontact beacons & unable to find those beacons when i starts ranging. 

but i have some Kontact old beacons & they are coming in ranging.

i am using below code to specify my Kontact beacon Layout. please tell me a suitable layout so that i can find my newly purchased Kontact beacon also in ranging.

beaconManager.getBeaconParsers().add(new BeaconParser().setBeaconLayout("m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24,d:25-25"));

Please help me it's very urgent.

**Comment by davidgyoung** [comment]
@kiledar2006, I cannot tell you why your new Kontact beacons are not working because I cannot see what they are transmitting.  You would need to check with Kontact.io if they have changed their beacon transmission.  If you wish, you might be able to figure out the layout by turning on debugging with `beaconManager.setDebug(true)` and then posting a LogCat capture while ranging to a Gist.  

If you decide to do this, please post this as a new question to StackOverflow.com as this forum is reserved for feature requests and reporting reproducible bugs with the library.

Also, apologies, but I have redacted the details of the layout in your question, because it is Apple proprietary information which may not be displayed in this open source project.
