### ISSUE TITLE
Please Explain Beacon Layout 

### ISSUE THREAD

**Issue by kiledar2006** [AltBeacon/android-beacon-library#226]
Hello,

"m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24,d:25-25"

i am using this beacon layout for Kontakt beacons, it's working fine. but i want to know what is the exact meaning of this layout.

pls explain what is the meaning of below values & how would i get these values from my beacons :- 

1. m:2-3=0215, 
2. i:4-19
3. i:20-21
4. i:22-23
5. p:24-24
6. d:25-25

**Comment by davidgyoung** [comment]
Sorry, @kiledar2006, but this is question is about a proprietary beacon format.  Because this is intellectual property, and this repo is open source, we cannot post this kind of information in this forum.    I have redacted the question to remove the proprietary information.  

You can read more about the beacon layout here: http://altbeacon.github.io/android-beacon-library/javadoc/org/altbeacon/beacon/BeaconParser.html
