### ISSUE TITLE
iBeacons not detected

### ISSUE THREAD

**Issue by AppleDeveloper98** [AltBeacon/android-beacon-library#298]
Hi,

I have integrate the AltBeacon Library in my app but this doesn't detect the iBeacon. What are I doing wrong?

Here the code:
```java
private BeaconManager beaconManager;
@Override
    protected void onCreate(Bundle savedInstanceState) {
        beaconManager = BeaconManager.getInstanceForApplication(this);
        beaconManager.getBeaconParsers().add(new BeaconParser().
                setBeaconLayout("m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24")); //iBeacon
        beaconManager.bind(this);
    }

@Override
    public void onBeaconServiceConnect() {
        beaconManager.setMonitorNotifier(new MonitorNotifier() {
        @Override
        public void didEnterRegion(Region region) {
            Log.i(TAG, "I just saw an beacon for the first time!");        
        }

        @Override
        public void didExitRegion(Region region) {
            Log.i(TAG, "I no longer see an beacon");
        }

        @Override
            public void didDetermineStateForRegion(int state, Region region) {
            Log.i(TAG, "I have just switched from seeing/not seeing beacons: "+state);        
            }
        });

        try {
            beaconManager.startMonitoringBeaconsInRegion(new Region("11111111-1111-1111-1111-111111111111", null, null, null));
        } catch (RemoteException e) {    }
    }
```

The same beacons with the same configuration working well under iOS.

The Log show only endless:
D/BluetoothAdapter﹕ startLeScan(): null
 D/BluetoothAdapter﹕ stopLeScan()

What I'm doing wrong and how can I fix it?

Thanks for help!
Nils

**Comment by davidgyoung** [comment]
@AppleDeveloper98, for help in using this library, please open a question on Stackoverflow.com.   This forum is reserved for feature requests and reproducible bugs with the library itself.  When opening your question on StackOverflow.com, please also report whether the Locate Beacon app will detect your beacon when running on the same device.  https://play.google.com/store/apps/details?id=com.radiusnetworks.locate&hl=en

Also, apologies but I had to redact part of your question, because we cannot publish the layouts of proprietary beacon formats in this open source format without permission of the beacon format owner.
