### ISSUE TITLE
Does Android BLE scanner ask scan response by default?

### ISSUE THREAD

**Issue by lixiaoqi** [AltBeacon/android-beacon-library#30]
Hi~I'm using Nexus 5 to test AltBeacon and I find that the length of byte[] scanRecord is 62. The BLE spec says that max length of advertisement data is 31 bytes. Does it mean that Android ask scan response by default when it is scanning?

Thank you~

**Comment by hieuvt6-fti** [comment]
Sorry for necroposting, but since I was led here by Google, I just want to clarify in case someone looking for information ended up here (while you might already know the facts now).

Of the 62 bytes. 31 are from the advertising packet, and 31 are from the scan response packet.
The reason you always have the last 31 bytes to be 0 is merely because the advertiser does not have a scan response. 
I don't remember if an empty scan response results in entire 31 bytes of 0, because 2 of them are used for header purpose.

**Comment by andrea-nisti** [comment]
Again, sorry for necroposting. Is it possible to add a scan response to a beacon packet, say an iBeacon, with android beacon library?

**Comment by davidgyoung** [comment]
The AndroidBeaconLibrary does not include tools to add a scan response with the BeaconTransmitter utility class.  However, Android does supply a way of setting the scan response here: https://developer.android.com/reference/android/bluetooth/le/BluetoothLeAdvertiser.html#startAdvertising(android.bluetooth.le.AdvertiseSettings,%20android.bluetooth.le.AdvertiseData,%20android.bluetooth.le.AdvertiseData,%20android.bluetooth.le.AdvertiseCallback)

So in theory you could modify the library to do this.  If you are interested in working on this and submitting a pull request, please open a new issue and I can give you tips on how to proceed.

**Comment by andrea-nisti** [comment]
alright, thanks a lot! I will check the pure android method and implement a working solution and after that, I will try to add this functionality to the library

**Comment by gvfbossa** [comment]
Hi, I am trying to scan for a device that needs a filter to be found.
Using an app such as nrf Connect, and putting in the filter: 02010612435542, returns me the devices on scan. 
I saw davidgyoung mentioning the scan record of 62 bytes, beggining with 0201061.....
Is there any pattern on it? since it begins the same as mine. I know there is the manufacturer ID and the manufacturer data. Can you please tell me which one is which? How do I decode this filter/EIR ? I am having a hard time trying to scan it but nothing seems to work. Thanks in advance.
