### ISSUE TITLE
Cannot transmit on Nexus 6 under Marshmallow 

### ISSUE THREAD

**Issue by arickatz** [AltBeacon/android-beacon-library#307]
I tried using the code in eclipse everything compiles and the mBeaconTransmitter.checkTransmissionSupported(getApplicationContext()) returns 0 or
the callback returns success, yet I cannot see the advertised beacon.

I used the quickbeacon app and from it I could see the beacon.
what am I missing?

this is my Estimote option and tried the radius one as well
mBeaconTransmitter = new BeaconTransmitter(this, new BeaconParser().setBeaconLayout("**REDACTED**"));
			// Transmit a beacon with Identifiers 2F234454-CF6D-4A0F-ADF2-F4911BA9FFA6 1 2
			Beacon beacon = new Beacon.Builder()
		              .setId1("B9407F30-F5F8-466E-AFF9-25556B57FE6D")
		              .setId2("1")
		              .setId3("2")
		              .setManufacturer(0x015D) // Choose a number of 0x00ff or less as some devices cannot detect beacons with a manufacturer code > 0x00ff
		              .setTxPower(-59)
		              .setDataFields(Arrays.asList(new Long[] {0l}))
		              .build();
mBeaconTransmitter.startAdvertising(beacon);

**Comment by davidgyoung** [comment]
Apologies, I had to redact the beacon parser expression in your question because it is proprietary and we cannot post proprietary info in this open source project as it is licensed under Apache 2.  

I suspect your problem has to do with the manufacturer code.  For certain beacon types, the manufacturer code has to be set to the two byte code for company sponsoring the beacon format, and not the actual manufacturer of the beacon itself.  

Sorry again for being a bit vague, but we cannot directly provide instructions for how to advertise or detect proprietary beacon formats without permission of the format's sponsor.
