### ISSUE TITLE
Can your library to scan ibeacon?

### ISSUE THREAD

**Issue by zentechthaingo** [AltBeacon/android-beacon-library#311]
I want to scan both Eddystone and Ibeacon. Can I do that with you library ?

**Comment by davidgyoung** [comment]
Yes, the library can scan both kinds of beacons, but you must provide a new `BeaconParser` with the proper layout expression for proprietary beacons.  Because iBeacon is proprietary, its layout is not included in the open source library.  For more help on finding this, search Google or Stackoverflow.com.

**Comment by zentechthaingo** [comment]
Thanks :+1:
