### ISSUE TITLE
When monitoring all regions, uuid is null

### ISSUE THREAD

**Issue by leeweijie** [AltBeacon/android-beacon-library#415]
###Expected behavior
UUID received in didEnterRegion() for beacon monitoring
###Actual behavior
calling region.getId1() gives null
###Steps to reproduce this behavior
1) Use bootstrap notifier
2) Initialise bootstrapregion by passing a region with null uuid, id1 and id2. (detect all beacons)
###Mobile device model and OS version
Android 6.0
###Android Beacon Library version
2.9

**Comment by davidgyoung** [comment]
This is expected behavior as designed.  The monitoring APIs return a reference to the same `Region` object used to start monitoring.  So if you use all null wildcards in this `Region`, that is what you get back.  You can use ranging APIs to find the identifiers of the specific beacons detected.  

If you need more help using the library, please open a new question on StackOverflow.com.
