### ISSUE TITLE
Duplicated iBeacons

### ISSUE THREAD

**Issue by pascalbros** [AltBeacon/android-beacon-library#433]
### Expected behavior
Let's say there are 2 iBeacons with the same UUID, Major and Minor, in the BeaconConsumer, I expect to have 2 beacons returned (with different RSSI)
### Actual behavior
It returns just one beacon.

### Steps to reproduce this behavior
Setup 2 beacons with the same configuration and scan for it.
### Mobile device model and OS version
Any model
### Android Beacon Library version
Latest

**Comment by davidgyoung** [comment]
Hi, @pascalbros, this behavior is actually configurable with the library.  If you want the expected behavior you describe simply call the `Beacon.setHardwareEqualityEnforced(true)` method:

https://altbeacon.github.io/android-beacon-library/javadoc/org/altbeacon/beacon/Beacon.html#setHardwareEqualityEnforced(boolean)

The reason this behavior is not default with the library is that it was added after the 2.0 release, and making it default would be a breaking change to the API.
