### ISSUE TITLE
Scanning issue

### ISSUE THREAD

**Issue by arpitjoshi08** [AltBeacon/android-beacon-library#477]
Getting scanning issue even blutooth off then its printing "BluetoothAdpater is Enable" or disable something...
  i think its may cause battery consumption.  
see this 
03-08 14:14:19.677  28622-28622/org.altbeacon.beaconreference D/BluetoothAdapter﹕ isEnabled
03-08 14:14:20.780  28622-28622/org.altbeacon.beaconreference D/BluetoothAdapter﹕ isEnabled
03-08 14:14:21.882  28622-28622/org.altbeacon.beaconreference D/BluetoothAdapter﹕ isEnabled
03-08 14:14:22.995  28622-28622/org.altbeacon.beaconreference D/BluetoothAdapter﹕ isEnabled
03-08 14:14:24.104  28622-28622/org.altbeacon.beaconreference D/BluetoothAdapter﹕ isEnabled
03-08 14:14:25.204  28622-28622/org.altbeacon.beaconreference D/BluetoothAdapter﹕ isEnabled
03-08 14:14:26.306  28622-28622/org.altbeacon.beaconreference D/BluetoothAdapter﹕ isEnabled
03-08 14:14:27.406  28622-28622/org.altbeacon.beaconreference D/BluetoothAdapter﹕ isEnabled
03-08 14:14:28.523  28622-28622/org.altbeacon.beaconreference D/BluetoothAdapter﹕ isEnabled
03-08 14:14:29.624  28622-28622/org.altbeacon.beaconreference D/BluetoothAdapter﹕ isEnabled
03-08 14:14:30.726  28622-28622/org.altbeacon.beaconreference D/BluetoothAdapter﹕ isEnabled
 happening in 6.0 lenovo device

**Comment by davidgyoung** [comment]
Unfortunately the Android bluetooth stack is notoriously chatty in the logs, and it spits out this message each time the library checks to see if bluetooth is enabled when starting a scan cycle to prevent a crash if it is not.

The logging will use some battery, but will probably be negligible since it only happens (with default settings) once per second when the app is in the foreground and once every 5 minutes when the app is in the background on Android 4/5 and rarely in the background on Android 6.  

If you think the above analysis is wrong, I'd encourage you to run tests to see if this check does in deed use a measurable amount of power. Please reopen if so.
