### ISSUE TITLE
startRangingBeaconsInRegion kills WiFi on Moto G, perhaps

### ISSUE THREAD

**Issue by quitequick** [AltBeacon/android-beacon-library#49]
It appears that as soon as I beaconManager.startRangingBeaconsInRegion, wifi becomes broken on a Moto G. I realise this may be a Moto G thing rather than an AltBeacon thing - but I would be interested to hear your thoughts...

**Comment by victorraft** [comment]
Does anyone know any workaround for this problem? 
Do you think if I toggle the beacon scan periodically it will work? If so, how much time do you recommend?

**Comment by davidgyoung** [comment]
You can try that technique but I doubt it will prove reliable.  The issue is it be a problem the other way -- WiFi connevtions can also break beacon detections.

I think your best net would be to get administrative privileges for WiFi, and if it is on, prompt the user to allow you to turn off wifi when running the app.  Then turn it back on when the app exits.
