### ISSUE TITLE
Beacon Parser

### ISSUE THREAD

**Issue by Sydney-o9** [AltBeacon/android-beacon-library#517]
# This works well :

````
 setBeaconLayout("m:0-3=4c000215,i:4-19,i:20-21,i:22-23,p:24-24"));
````

It will match all iBeacons properly which is great:
- Bytes 0-3 for Apple iBeacon: (0x4c) (0x00) (0x02) (0x15)
- Bytes 4-19 for UUID
- Bytes 20-21 for Major Value
- Bytes 22-23 for Minor Value
- Byte 24 for Measured Power

# This is not possible :

If Person A wishes to add another layer of filtering on the UUID, for example:
- Byte 4 and 5 will always be (0x1a) (0x1b) by convention for all beacons installed by Person A

````
 setBeaconLayout("m:0-5=4c0002151a1b,i:4-19,i:20-21,i:22-23,p:24-24"));
````

This fails when the beacon is detected:

<img width="759" alt="screen shot 2017-05-29 at 4 35 09 pm" src="https://cloud.githubusercontent.com/assets/1480617/26538911/dd65ccfe-448c-11e7-8b79-a5eed90d5342.png">

Is there any way to currently add this level of filtering?

**Comment by davidgyoung** [comment]
@Sydney-o9, the problem is that you cannot set a BeaconLayout's matching pattern to be more than four bytes.  The matching pattern is designed to match a beacon type, which is typically only two bytes.   It is not designed to match partial identifier patterns.

If you want to only match beacons based on the full most significant identifier (a very common use case), then this is what `Regions` are designed to do.  The following definition will match a primary UUID identifier of 1a1b0000-0000-0000-000000000000, you can do so with:

```
Region region = new Region("1a1b0000-0000-0000-000000000000", null, null);
```

This, however, will only match the *full* UUID shown above with all zeroes at the end, so it won't work if you want to match a partial identifier.  If you really want to match a partial identifier, you can define a nonstandard custom beacon parser to make the first identifier just be two bytes like this:

```
setBeaconLayout("m:2-3=beac,i:4,5,i:4-19,i:20-21,i:22-23,p:24-24,d:25-25"));
```
and then you can define your region like this:

```
Region region = new Region("myapp.region2", Identifier.parse("0x1a1b"), null, null);
```

This basically defines a first identifier (see the i:4-5 part of the layout) as only the first two bytes of the identifier space.  When you detect the beacon with Ranging APIs, it will have four identifiers, the first is the first two bytes, the second is the UUID, the third is the major and the fourth is the minor.

**IMPORTANT NOTE**: The example BeaconLayout above starting with m:2-3=beac is the matching pattern for the AltBeacon layout.  If you want to use a proprietary layout like mentioned in your question, you'll need to replace that part with the proprietary matcher for your beacon type.

As for the library's handling of your test case above, clearly throwing an exception at runtime is bad. 
 This should  show up as a more descriptive error message about why this is not allowed at the time the BeaconParser is created, rather than crashing at the time the beacon is detected.  I'll leave this issue open for a fix there.
