### ISSUE TITLE
Invalid identifiers when scanning for beacons?

### ISSUE THREAD

**Issue by a-dev-has-no-name** [AltBeacon/android-beacon-library#597]
### Expected behavior
The following is an example of an (actual) valid beacon:
id1: f2356731-fbd4-4a10-8aa2-c89adf48a98d
id2: 6262
id3: 202

### Actual behavior
The following are (actual) examples of the 2 types of invalid beacons I'm seeing (assuming they are beacons at all):

#### example 1:
id1: 0x026d726566657200313835343333323035
id2: doesn't exist 
id3: doesn't exist 

#### example 2:
id1: 0x08a4cef96bcaf67d5f34
id2: 0x6bc2e6f748ce 
id3: doesn't exist 

### Steps to reproduce this behavior
Not entirely sure why this is happening, but I am scanning for all beacons `new Region("all-beacons-region", null, null, null)` using the alt beacon layout and all three eddystone layouts from the `BeaconParser` class. I'm also using the ibeacon layout.  

### Mobile device model and OS version
Several models and OS models, testing on hundreds of devices in an app

### Android Beacon Library version
2.12.1

Is there any solution for this? Is this expected to happen for some beacons? Is it deliberate on the part of those deploying the beacons, possibly? Any help would be appreciated, thanks!!!

**Comment by davidgyoung** [comment]
I believe this is expected behavior.  In the three examples shown:

* example 1 is a Eddystone-URL beacon with the first identifier the encoded URL.  There are no second or third identifiers for this beacon type.
* example 2 is a Eddystone-UID beacon with the first identifier the namespace id and the second identifier the instance id.   There is no third identifier for this beacon type.

When using a wildcard region it will match beacons with all identifiers regardless of type.
