### ISSUE TITLE
Background & foreground detection

### ISSUE THREAD

**Issue by xdeop** [AltBeacon/android-beacon-library#624]
Hi I would like a bit more explanation (and help) about background and foreground beacons detection:

If we want our app to detect beacons when it's opened (foreground) and after it's closed (background), do we have to implement the "MonitoringActivity sample" (bind/unbind a custom beacon consumer) and in the Activity's onDestroy method create the RegionBootstraps? Or it's enough with just the background monitoring code, creating the RegionBootstrap on Application onCreate method? Or how it should be done?

Thanks.

**Comment by davidgyoung** [comment]
Use RegionBootstrap only if you want to detect after the app is killed or
after phone restart.

Otherwise, you can follow the Monitoring sample code.

If you need more assistance, please open a question on StackOverflow.com.
happy to answer there.


On Nov 24, 2017 6:10 AM, "xdeop" <notifications@github.com> wrote:

Hi I would like a bit more explanation (and help) about background and
foreground beacons detection:

If we want our app to detect beacons when it's opened (foreground) and
after it's closed (background), do we have to implement the
"MonitoringActivity sample" (bind/unbind a custom beacon consumer) and in
the Activity's onDestroy method create the RegionBootstraps? Or it's enough
with just the background monitoring code, creating the RegionBootstrap on
Application onCreate method? Or how it should be done?

Thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/AltBeacon/android-beacon-library/issues/624>, or mute
the thread
