### ISSUE TITLE
is device location compulsory to scan beacons?

### ISSUE THREAD

**Issue by aashu09** [AltBeacon/android-beacon-library#698]
### Expected behavior
Beacon should not depend on device location. As device location draining too much battery.

### Actual behavior
Beacon using location for scanning and because of this device battery draining too much battery.

Please suggest me about location use in beacon scanning, I don't want to use location to save battery of my device.

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
Don't confuse the Android Location setting with the GPS radio.  This library requires location to be turned on with Android 6+ because the location setting must be turned on for beacons to be scanned.  This is a decision made by Google engineers for the Android operating system.  But just because the user must turn on Location does not mean that the GPS radio is on at all.  And while GPS scanning may use a large amount of battery if done for long periods of time without stopping, this library does not do that with default settings.
