### ISSUE TITLE
Crash on oreo

### ISSUE THREAD

**Issue by priteshyugtia** [AltBeacon/android-beacon-library#779]
I got crash when kill app in android oreo 8.1.0 and i am using org.altbeacon:android-beacon-library:2.15.2 version

Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.altbeacon.beaconreference/org.altbeacon.beacon.service.BeaconService }: app is in background uid UidRecord{6b25193 u0a144 RCVR idle change:uncached procs:1 seq(0,0,0)}

**Comment by davidgyoung** [comment]
Are you configuring the library to use a foreground service?  If not, have you disabled scan jobs?

On Android 8+, you will get the crash you describe if you disable scan jobs but do not properly configure the library to use a foreground service.  Android 8+ does not allow starting a background IntentService to do scanning, which is why the library uses scan jobs by default on Android 8+.

See #719 for details.

**Comment by priteshyugtia** [comment]
Are you configuring the library to use a foreground service? 
- Yes, I want to scan beacon in background. Actually foreground service is working fine but i need to work in background.

If not, have you disabled scan jobs?
- I have disable job. Just see below code sample
beaconManager.setEnableScheduledScanJobs(false);
beaconManager.setBackgroundBetweenScanPeriod(0);
beaconManager.setBackgroundScanPeriod(1100);

- Background process will take time to scan beacon and not showing beacons.

**Comment by kavin626** [comment]
i cant use the method  beaconManager.enableForegroundServiceScanning(builder.build(), 456);in android.it showing  red color error
