### ISSUE TITLE
Background notification does not disappear

### ISSUE THREAD

**Issue by edysolisaritec** [AltBeacon/android-beacon-library#802]
### Expected behavior

When I close my application or stop the search service the notification disappears

### Actual behavior

I close, I kill the process of the application and the continuous notification

### Steps to reproduce this behavior

close application and kill the process

### Mobile device model and OS version

Huawei P20 lite Android 8.0, Samsung Galaxy S7 android 8.0 and Google Pixel XL android 9.0

### Android Beacon Library version

org.altbeacon:android-beacon-library:2.15.4

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
When you configure this library to work with a foreground service, then swiping the app off the screen with the task switcher will *not* kill the app.  It continues running, and the beacon scanning service continues running.  That is why you see the service notification still appear.   In order to stop the app, you must provide a UI widget to gesture to to actually stop it.  In your code that handles the gesture you must:

* Stop the foreground service (unbind from the BeaconManager or use the disable method of RegionBootsrap)
* Call finishAffinity() on your activity if you really want your app to shut all the way down.
