### ISSUE TITLE
Wellcore beacon is not detecting at all

### ISSUE THREAD

**Issue by sitaram-gupta** [AltBeacon/android-beacon-library#866]
### Expected behavior
To detect the wellcore beacon wiith this project: https://github.com/AltBeacon/android-beacon-library-reference 

Radius network beacon is working fine.
### Actual behavior
No any response for wellcore beacon.
but its detecting in BeaconScope App
### Mobile device model and OS version
Redmi 4x   OS Version:- 7.1.1
### Android Beacon Library version
2.16.1
IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
@sitaram-gupta, since you can detect the beacon with the BeaconScope app (which also is built using this library) that means that if you properly configure the library it will detect that beacon. You likely need to simply setting the iBeacon layout with:

`beaconManager.getBeaconParsers().add(new BeaconParser(). setBeaconLayout("m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24"));`

Please give that a shot and if it does not work, open a question on StackOverflow.com.  This forum is reserved for bug reports and feature requests and is not designed for general assistance building apps with this library.
