### ISSUE TITLE
Crash in ScanJob.java line 145 onStartJob()

### ISSUE THREAD

**Issue by matdev** [AltBeacon/android-beacon-library#963]
### Expected behavior
No crash

### Actual behavior
Crashes are seen occuring in our app's Crashlytics console
Surprisingly, there is no stack trace available in Crashlytics

### Mobile device model and OS version
Android 8 (BQ, LGE)

### Android Beacon Library version
2.16.4

**Comment by davidgyoung** [comment]
Unfortunately, without additional information including an Exception type, a proper line number and a stack trace, there is nothing that can be done to track this down.   Line number 145 of ScanJob.java is whitespace in the source file for 2.16.4, so even that single detail is suspect.   

If you can gather more information, please open a new issue.  But since there is insufficient information to investigate, there is no point in leaving an unresolvable issue open.

**Comment by matdev** [comment]
I understand, I'll you know if I manage to get the stacktrace.
For info, all of these crashes occured when app is in background
